name: Test

on:
  push

jobs:
  test:
    runs-on: alpine-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: ./